### ISSUE TITLE
Webhook integration

### ISSUE THREAD

**Issue by mb243** [bittiez/HelpOp-Email#2]
Please consider adding support for webhook notifications, with the potential for notifying several webhooks on a single request. This would allow user-configurable notifications into services like Discord, Slack, etc. 

Resources you may find helpful:

- https://discordapp.com/developers/docs/resources/webhook
- https://api.slack.com/incoming-webhooks

**Comment by bittiez** [comment]
Done with Discord with release 2.2.0
